version: '3.8'

services:
  web:
    build: .
    command: bash -c "python manage.py check --database default && python manage.py migrate && gunicorn Helldivers_2_Database.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - ./Helldivers_2_Database:/app/Helldivers_2_Database
      - ./Ressources:/app/Ressources
      - ./templates:/app/templates
      - ./manage.py:/app/manage.py
      - ./import_json_data.py:/app/import_json_data.py
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
