# Generated by Django 4.2 on 2025-05-06 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_factions_faction_alter_faction_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArmorPassive',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Armor Passive',
                'verbose_name_plural': 'Armor Passives',
                'db_table': 'armor_passives',
            },
        ),
        migrations.CreateModel(
            name='ArmorSlot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Armor Slot',
                'verbose_name_plural': 'Armor Slots',
                'db_table': 'armor_slots',
            },
        ),
        migrations.CreateModel(
            name='Biome',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Biome',
                'verbose_name_plural': 'Biomes',
                'db_table': 'biomes',
            },
        ),
        migrations.CreateModel(
            name='Booster',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Booster',
                'verbose_name_plural': 'Boosters',
                'db_table': 'boosters',
            },
        ),
        migrations.CreateModel(
            name='Environmental',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Environmental',
                'verbose_name_plural': 'Environmentals',
                'db_table': 'environmentals',
            },
        ),
        migrations.CreateModel(
            name='FireMode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Fire Mode',
                'verbose_name_plural': 'Fire Modes',
                'db_table': 'fire_modes',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Sector',
                'verbose_name_plural': 'Sectors',
                'db_table': 'sectors',
            },
        ),
        migrations.CreateModel(
            name='WeaponTrait',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Weapon Trait',
                'verbose_name_plural': 'Weapon Traits',
                'db_table': 'weapon_traits',
            },
        ),
        migrations.CreateModel(
            name='WeaponType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Weapon Type',
                'verbose_name_plural': 'Weapon Types',
                'db_table': 'weapon_types',
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('damage', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(default=0)),
                ('recoil', models.IntegerField(default=0)),
                ('fire_rate', models.IntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_secondary', models.BooleanField(default=False)),
                ('is_grenade', models.BooleanField(default=False)),
                ('fire_modes', models.ManyToManyField(related_name='weapons', to='api.firemode')),
                ('traits', models.ManyToManyField(related_name='weapons', to='api.weapontrait')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weapons', to='api.weapontype')),
            ],
            options={
                'verbose_name': 'Weapon',
                'verbose_name_plural': 'Weapons',
                'db_table': 'weapons',
            },
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('name_en_US', models.CharField(blank=True, max_length=200, null=True)),
                ('name_en_GB', models.CharField(blank=True, max_length=200, null=True)),
                ('name_pt_BR', models.CharField(blank=True, max_length=200, null=True)),
                ('name_de_DE', models.CharField(blank=True, max_length=200, null=True)),
                ('name_es_ES', models.CharField(blank=True, max_length=200, null=True)),
                ('name_fr_FR', models.CharField(blank=True, max_length=200, null=True)),
                ('name_it_IT', models.CharField(blank=True, max_length=200, null=True)),
                ('name_ja_JP', models.CharField(blank=True, max_length=200, null=True)),
                ('name_ko_KO', models.CharField(blank=True, max_length=200, null=True)),
                ('name_ms_MY', models.CharField(blank=True, max_length=200, null=True)),
                ('name_pl_PL', models.CharField(blank=True, max_length=200, null=True)),
                ('biome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planets', to='api.biome')),
                ('environmentals', models.ManyToManyField(related_name='planets', to='api.environmental')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planets', to='api.sector')),
            ],
            options={
                'verbose_name': 'Planet',
                'verbose_name_plural': 'Planets',
                'db_table': 'planets',
            },
        ),
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.IntegerField(default=0)),
                ('armor_rating', models.IntegerField(default=100)),
                ('speed', models.IntegerField(default=100)),
                ('stamina_regen', models.IntegerField(default=100)),
                ('passive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armors', to='api.armorpassive')),
                ('slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='armors', to='api.armorslot')),
            ],
            options={
                'verbose_name': 'Armor',
                'verbose_name_plural': 'Armors',
                'db_table': 'armors',
            },
        ),
    ]
