image: python:3.9

stages:
  - test
  - lint
  - deploy

before_script:
  - pip install -r requirements.txt

test:
  stage: test
  script:
    - python manage.py test

lint:
  stage: lint
  script:
    - pip install flake8
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server"
  only:
    - develop

deploy_production:
  stage: deploy
  script:
    - echo "Deploy to production server"
  only:
    - main