name: Database Migrations

on:
  push:
    branches: [ main, develop ]
    paths:
      - '*/migrations/*.py'
      - '*/models.py'

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run Migrations
      run: |
        python manage.py migrate
        
    - name: Check for migration issues
      run: |
        python manage.py makemigrations --check --dry-run
        
  backup-db:
    runs-on: ubuntu-latest
    needs: migrate
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
    
    - name: Backup Database
      run: |
        echo "Creating database backup before applying migrations..."
        # In a real scenario, you would add database backup steps here
        # For example, using pg_dump for PostgreSQL or mysqldump for MySQL