name: Security Scanning

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  schedule:
    - cron: '0 0 * * 0'  # Run weekly on Sunday at midnight

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bandit safety
    
    - name: Run Bandit (Python Security Scanner)
      run: |
        bandit -r . -x ./tests,./venv -f json -o bandit-results.json || true
    
    - name: Check for vulnerable dependencies
      run: |
        safety check -r requirements.txt --json > safety-results.json || true
    
    - name: Upload scan results
      uses: actions/upload-artifact@v2
      with:
        name: security-scan-results
        path: |
          bandit-results.json
          safety-results.json
    
    - name: Fail if high severity issues found
      run: |
        if grep -q '"issue_severity": "HIGH"' bandit-results.json; then
          echo "High severity security issues found in code!"
          exit 1
        fi
        if grep -q '"severity": "high"' safety-results.json; then
          echo "High severity vulnerabilities found in dependencies!"
          exit 1
        fi